# Kustomize setup of the resources, that would be common for all environments
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common resource metrics-server is deployed into kube-system namespace - not same as the namespaces of the apps
namespace: kube-system

components:
  - ../../../base


