apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envapp
  name: envapp-envapp
spec:
  selector:
      matchLabels:
        app: envapp
  template:
    spec:
      containers:
        - name: envapp
          env:
            - name: PROD
              value: "true"

