#!/bin/bash
######################################################
# Usage Notes:
# This is a utility script and it'll be triggered / 
# called by the helm CLI, when helm's --post-renderer
# flag is used and references this script
#
# helm ...(will output generated yaml)... | kustomize.sh
# ^-- Imagine that the yaml wall of text generated by helm
#     will become stdin for this script
#     the contents of stdin will be put in a temp file
#     (because `kustomize build .` will expect a file to exist)
#     Then the temp file will be removed after being
#     used by kustomize for post rendering purposes
#
# remember `-` is bash representation of stdin
######################################################
cat - > helm-generated-output.yaml
kustomize build . && rm helm-generated-output.yaml
